import { randomUUID } from 'node:crypto';

/**
 * Auth OTP delivery mode (Ticket 27A / R0).
 *
 * Two explicit modes replace the old ambiguous `OTP_DEMO_REVEAL` switch:
 *
 *  - `demo`     — no real SMS/email is sent. The generated code is remembered in
 *                 memory *only for allowlisted, non-personal demo contacts* so the
 *                 UI can auto-fill it. Better Auth still verifies the code and mints
 *                 the session; the demo never bypasses verification.
 *  - `provider` — real delivery. No vendor is wired in R0 (Resend/MSG91/DLT are
 *                 Ticket 27B, provider-blocked), so `deliverOtp` throws: sends fail
 *                 CLOSED and the UI never falsely claims a message was sent.
 *
 * Default (unset/invalid) is `provider` → fail closed. `demo` must be turned on
 * explicitly and only in the confirmed Sahi case-study environment (which is the
 * sole place `AUTH_DELIVERY_MODE=demo` is ever set).
 */
export type AuthDeliveryMode = 'demo' | 'provider';

export function getAuthDeliveryMode(): AuthDeliveryMode {
  return process.env.AUTH_DELIVERY_MODE === 'demo' ? 'demo' : 'provider';
}

type Channel = 'email' | 'phone';

const OTP_TTL_MS = 300_000; // 5 min — matches Better Auth's expiresIn.

/** Storage key: emails are case-folded; phones are compared as sent (E.164). */
function storeKey(channel: Channel, contact: string): string {
  const c = contact.trim();
  return channel === 'email' ? c.toLowerCase() : c;
}

/** The accepted comparison forms of a contact (raw-trimmed and case-folded). */
function contactForms(contact: string): string[] {
  const c = contact.trim();
  const lower = c.toLowerCase();
  return c === lower ? [c] : [c, lower];
}

/** Allowlisted demo contacts from `DEMO_OTP_CONTACTS` (comma-separated). */
export function allowedDemoContacts(): Set<string> {
  const set = new Set<string>();
  for (const entry of (process.env.DEMO_OTP_CONTACTS ?? '').split(',')) {
    const e = entry.trim();
    if (!e) continue;
    set.add(e);
    set.add(e.toLowerCase());
  }
  return set;
}

export function isDemoContactAllowed(contact: string): boolean {
  const allow = allowedDemoContacts();
  return contactForms(contact).some((f) => allow.has(f));
}

const store = new Map<string, { code: string; expiresAt: number }>();

/** Remember a demo OTP — only in demo mode, only for an allowlisted contact. */
export function recordDemoOtp(channel: Channel, contact: string, code: string): void {
  if (getAuthDeliveryMode() !== 'demo') return;
  if (!isDemoContactAllowed(contact)) return;
  store.set(storeKey(channel, contact), { code, expiresAt: Date.now() + OTP_TTL_MS });
}

/**
 * Return the last demo OTP for a contact, or null. Gated to demo mode +
 * allowlisted contact + not expired. Every other contact gets a uniform null,
 * so an arbitrary caller can never retrieve or enumerate an OTP.
 */
export function peekDemoOtp(contact: string): string | null {
  if (getAuthDeliveryMode() !== 'demo') return null;
  if (!isDemoContactAllowed(contact)) return null;
  for (const key of contactForms(contact)) {
    const hit = store.get(key);
    if (!hit) continue;
    if (hit.expiresAt <= Date.now()) {
      store.delete(key);
      continue;
    }
    return hit.code;
  }
  return null;
}

/** Test/ops helper: clear the in-memory demo store (also emptied on restart). */
export function resetDemoOtpStore(): void {
  store.clear();
}

/**
 * Handle an OTP generated by Better Auth. In demo mode: store for allowlisted
 * contacts and emit a PII-free event. In provider mode: throw (fail closed) — no
 * real vendor exists in R0. Never logs the contact or the code.
 */
export function deliverOtp(channel: Channel, contact: string, code: string): void {
  void code; // never logged; stored only via recordDemoOtp for allowlisted demo contacts
  if (getAuthDeliveryMode() === 'provider') {
    throw new Error('OTP delivery provider is not configured');
  }
  recordDemoOtp(channel, contact, code);
  // Correlation id only — no phone, email or OTP in logs.
  console.log(`[auth] otp issued channel=${channel} mode=demo correlationId=${randomUUID().slice(0, 8)}`);
}
